---

name: CI
on: push

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: | 
	      pip install -r requirements.txt 
	      pip install --upgrade pip 
      - run: | 
          ls -la
          python Hello.py
          echo "The code is okay"
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt 
	  - run: pip install --upgrade pip
      - run: flake8 . --extend-exclude=dist,build --show-source --statistics
